baseURL = 'http://www.lenslanding.com/'
languageCode = 'en-us'
title = 'BetterViz'

[params]
  description = 'Interactive multi-dimensional data visualizer'

[markup.goldmark.renderer]
  unsafe = true
